CREATE TABLE SOZ_STAT_APPS (
  ID NUMBER(10) NOT NULL,
  NAME VARCHAR2(150 CHAR) NOT NULL,
  CONSTRAINT PK_SOZ_STAT_APPS PRIMARY KEY (ID))
TABLESPACE DIA_DATA
STORAGE (
  INITIAL 64K
  MAXEXTENTS UNLIMITED
)
LOGGING;

CREATE UNIQUE INDEX UK_SOZ_STAT_APPS_NAME ON SOZ_STAT_APPS (NAME)
TABLESPACE DIA_DATA
STORAGE (
  INITIAL 64K
  MAXEXTENTS UNLIMITED
)
LOGGING;

COMMENT ON COLUMN SOZ_STAT_APPS.ID IS 'App path identifier';
COMMENT ON COLUMN SOZ_STAT_APPS.NAME IS 'App path';

-- создаем последовательность для генерации ID
CREATE SEQUENCE SOZ_STAT_APPS_SQ
  START WITH 1
  INCREMENT BY 1;

-- создаем триггер для генерации ID
CREATE OR REPLACE TRIGGER SOZ_STAT_APPS_TRG_BEF_INS
BEFORE INSERT ON SOZ_STAT_APPS FOR EACH ROW
BEGIN
 IF :new.ID IS NULL THEN
		SELECT SOZ_STAT_APPS_SQ.nextval INTO :new.ID FROM DUAL;
	END IF;
END;